# Generated by Django 3.1.4 on 2020-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='offer',
            field=models.BooleanField(null=True),
        ),
    ]
